# Site settings
title: Wade Allen
email: wadesallen@gmail.com
description: "Hi, I am Wade Allen. I am a father, husband, son, friend and pastor. I live in Yorktown, Indiana and serve as Pastor at First Baptist Church (Muncie). "
baseurl: ""
url: "http://wadeallen.me"
twitter_username: wadeallen
github_username:  wadeallen
facebook_url: wadesallen
google_plus: +WadeAllen
instagram_username: wadechristy

# Build settings
markdown: kramdown
permalink: pretty
